name: lua_dardo
description: A Lua virtual machine written in Dart, which implements Lua5.3 version.
version: 0.0.3
homepage: https://github.com/arcticfox1919/LuaDardo.git

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  sprintf: "^5.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.7
